In [6]:
# Question 1

import numpy as np # Importing numpy

X = [3.67, 4 , 3 , 2.87, 2.9 , 4, 2.5 , 3.2, 3.8 , 2.9 , 2.91 ,3.6 ,2.6 ,3.2,4,3.1,2.4,3.213,3.76]
Y = [2.58, 2.7 , 3.4 , 3.65, 2.9 , 3, 3.5 , 4, 4 , 1.6 , 1.9 , 3.6 , 3.5 , 3.45,4,2.6,1.9,2.98,2.718]

a = np.array(X) # Converting the list of data X into numpy array
b = np.array(Y) # Converting the list of data Y into numpy array

print(a) # Printing numpy array a
print(b) # Printing numpy array b

n1 = len(a) 
n2 = len(b)

sumx = 0
for i in a: # Summing up the elements in array a using for loop
    sumx = sumx + i
print(f'The sum of elements all elements in X is {sumx}') # Printing the sum of all elements in X

x1bar = sumx / n1 # Calculating the mean of all elements in X
print(f'The mean of elements in X is {x1bar}') # Printing the mean of all elements in X

sumy = 0
for i in b: # Summing up the elements in array b using for loop
    sumy = sumy + i
print(f'The sum of elements all elements in Y is {sumy}') # Printing the sum of all elements in Y

x2bar = sumy / n2 # Calculating the mean of all elements in Y
print(f'The mean of elements in Y is {x2bar}') # Printing the mean of all elements in Y

var1 = 0
for x in a:# Calculating variance
    var1 = var1 + ((x- x1bar)**2)
    
var12 = var1/(n1-1)
print(f'The variance of data X is {var12}')

s1 = var12**0.5 # Calculating the standard deviation
print(f'The standard deviation of data X is {s1}')

var2 = 0
for x in b:# Calculating variance
    var2 = var2 + ((x- x2bar)**2)
    
var21 = var2/(n2-1)
print(f'The variance of data Y is {var21}')

s2 = var21**0.5 # Calculating the standard deviation
print(f'The standard deviation of data Y is {s2}')

numerator = x1bar - x2bar # Calculating the numerator

denom = (((n1-1)*(s1**2))+((n2-1)*(s2**2)))/(n1+n2-2) # Caculating the square of the denominator
denom1 = denom**0.5 # Calculating the denominator 
print(denom1)

d = abs(numerator/denom1) # Calculating cohen's d

print(f'Cohens d using X and Y is {d} ')

f = round(d,3) # Rounding of cohen's d to 3 decimal places
print(f'The rounded cohens d is {f}')

# Checking the effect size of cohens d
if f<=0.25:
    print(f'The effect size of {f} is small')
if 0.25<f<=0.4:
    print(f'The effect size of {f} is medium')
if f>0.4:
    print(f'The effect size of {f} is large')



[3.67  4.    3.    2.87  2.9   4.    2.5   3.2   3.8   2.9   2.91  3.6
 2.6   3.2   4.    3.1   2.4   3.213 3.76 ]
[2.58  2.7   3.4   3.65  2.9   3.    3.5   4.    4.    1.6   1.9   3.6
 3.5   3.45  4.    2.6   1.9   2.98  2.718]
The sum of elements all elements in X is 61.623000000000005
The mean of elements in X is 3.2433157894736846
The sum of elements all elements in Y is 57.97800000000001
The mean of elements in Y is 3.0514736842105266
The variance of data X is 0.2695566725146199
The standard deviation of data X is 0.5191884749439455
The variance of data Y is 0.5272768187134502
The standard deviation of data Y is 0.7261382917278569
0.6312026185101224
Cohens d using X and Y is 0.3039310985685994 
The rounded cohens d is 0.304
The effect size of 0.304 is medium


In [12]:
# Question 2

# Broading casting is when operations are performed between two numpy array which are not equal in size. 
# For broadcasting to be performed the rows and columns of both the arrays need to be compatible. 
# The rows of the two arrays have to be equal or one of them has to be 1 and the columns of the two matrices have to be 
# equal or one of them has to be 1. Only when this condition is satisfied broadcasting is possible.

import numpy as np

a = [[66,2,3],[2,4,54],[5,6,7],[7,8,9]]
b = [[1],[2],[3],[4]]
c = np.array(a) # Numpy array of shape 4 x 3
d = np.array(b) # Numpy array of shape 4 x 1
e = c+d # Broadcasting is possible as the number of rows of both the arrays are the same(that is 4). Eventhough the number of columns of the both the arrays are not the same, broadcasting is possible as array d has one column. The array's are compatible
print(e)

f = [[8,2,3],[2,3,5],[5,0,7],[7,1,9]]
g = [1,2,3,4]
h = np.array(f) # Numpy array of shape 4 x 3 
i = np.array(g) # Numpy array of shape 1 x 4
j = h+i # Broadcasting is not posible as the array's are not compatible. Array i has 1 row hence the condition for rows is staisfied, but the number of columns are not equal.
print(j)



[[67  3  4]
 [ 4  6 56]
 [ 8  9 10]
 [11 12 13]]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [55]:
# Question 3

import numpy as np

returns = np.array([0.02, -0.01, 0.015, -0.005, 0.025, -0.01, 0.03, -0.02, 0.015, 0.005])  # Numpy array of Portfolio Returns
returns

risk_free_rate = 0.04  # Annual Risk-Free Rate 4% per year 
daily_rate = risk_free_rate / 252  # Convert to daily risk-free rate
daily_rate

mean_returns = np.mean(returns)  # Mean of portfolio returns
std_dev = np.std(returns)  # Standard deviation

sharpe_ratio = (mean_returns - daily_rate) / std_dev   #  Computing the Sharpe Ratio
sharpe_ratio = round(sharpe_ratio,2)  # rounding the sharpe ratio to two decimal places

print('The sharpe ratio is:',sharpe_ratio)

The sharpe ratio is: 0.39


In [59]:
# Question 4:
import numpy as np

p = 0.36  # Frequency of the dominant allele
q = 1 - p  # Frequency of the recessive allele 
print(q)

# Computing Genotype Frequencies
homozygous_dominant = p**2  # Homozygous dominant (AA)
heterozygous = 2 * p * q  # Heterozygous (Aa)
homozygous_recessive = q**2  # Homozygous recessive (aa)

# Displaying the genotype frequencies
print("Homozygous dominant (AA):", round(homozygous_dominant, 2))
print("Heterozygous (Aa):", round(heterozygous, 2))
print("Homozygous Recessive (aa):", round(homozygous_recessive, 2))




0.64
Homozygous dominant (AA): 0.13
Heterozygous (Aa): 0.46
Homozygous Recessive (aa): 0.41
